### ISSUE TITLE
Коммент - после публикации не виден

### ISSUE THREAD

**Issue by Myxarules** [ko3a4ok/tolpa-ios#18]
Коммент - после публикации заменяет предыдущий. Например было 5 комментов- только что написанный становится 5 из 5 ти, а 5 вообще не видно, пока не обновишь страницу

**Comment by ko3a4ok** [comment]
I see the only correct behavior. 
![out](https://cloud.githubusercontent.com/assets/1435977/24635437/3b8763d2-1888-11e7-85ca-4e018733dab1.gif)

@Myxarules, Could you tell me, what is your device?
